version: '3.8'

services:
  user_service:
    build:
      context: .
      dockerfile: user_service/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "uvicorn app:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./user_service/src:/src

  task_service:
    build:
      context: .
      dockerfile: task_service/Dockerfile
    env_file:
      - .env
    ports:
      - "8001:8001"
    command: >
      sh -c "uvicorn app:app --host 0.0.0.0 --port 8001 --reload"
    volumes:
      - ./task_service/src:/src

  bots_service:
    build:
      context: .
      dockerfile: bots/Dockerfile
    env_file:
      - .env
    ports:
      - "8002:8002"
    command: >
      sh -c "uvicorn app:app --host 0.0.0.0 --port 8002 --reload"
    volumes:
      - ./bots/src:/src

  database:
    image: postgres:14.6-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    env_file:
      - .env

  elasticsearch:
    image: elasticsearch:8.16.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./bots/src:/app/bots
      - ./task_service/src:/app/task_service
      - ./user_service/src:/app/user_service

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  flower:
    image: mher/flower:1.2.0
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - redis
      - worker

volumes:
  db_data:
  rabbitmq_data:
  redis_data:
  esdata:
