version: '3.8'

services:
  bot_service:
    build:
      context: .
    env_file:
      - .env
    environment:
      - AUTO_RELOAD=true
    command: >
      sh -c "python main.py"
    volumes:
      - ./src:/app/src

  bot_redis:
    image: redis:7.0.5-alpine
    hostname: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    volumes:
      - bot_redis_data:/data

  bot_worker:
    build:  
      context: .
    env_file:
      - .env
    command: celery -A celery_app worker --loglevel=info --concurrency=${CELERY_WORKERS} -Q ${BOT_QUEUE}
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app/src
    depends_on:
      - bot_redis

volumes:
  bot_redis_data:
