"""cascade deleting for users_group table(if user or group will be deleted raws with deleted fks will be deleted in users_groups table)

Revision ID: fa4dfb772f42
Revises: 48058ee9ec29
Create Date: 2025-06-08 08:11:07.991601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa4dfb772f42'
down_revision: Union[str, None] = '48058ee9ec29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_groups_id'), 'groups', ['id'])
    op.create_unique_constraint(op.f('uq_users_id'), 'users', ['id'])
    op.drop_constraint(op.f('fk_users_groups_user_id_users'), 'users_groups', type_='foreignkey')
    op.drop_constraint(op.f('fk_users_groups_group_id_groups'), 'users_groups', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_groups_group_id_groups'), 'users_groups', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_users_groups_user_id_users'), 'users_groups', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_groups_user_id_users'), 'users_groups', type_='foreignkey')
    op.drop_constraint(op.f('fk_users_groups_group_id_groups'), 'users_groups', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_groups_group_id_groups'), 'users_groups', 'groups', ['group_id'], ['id'])
    op.create_foreign_key(op.f('fk_users_groups_user_id_users'), 'users_groups', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('uq_users_id'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_groups_id'), 'groups', type_='unique')
    # ### end Alembic commands ###
