from typing import Protocol, Optional
from datetime import timezone, datetime


class StorageInterface(Protocol):
    async def get_tz(self, tg_name: str) -> Optional[timezone]: ...
    async def set_tz(self, tg_name: str, offset: int) -> None: ...
    async def get_reminders_tab(self, tg_name: str) -> Optional[dict[str, datetime]]: ...
    async def get_reminder(self, tg_name: str, id_: str) -> Optional[datetime]: ...
    async def delete_reminder(self, tg_name: str, id_: str) -> None: ...
    async def set_reminder(self, tg_name: str, eta: datetime, id_: str) -> None: ...
