from typing import Protocol, Optional, overload, Awaitable
from datetime import timezone, datetime


class AsyncStorageInterface(Protocol):
    async def get_tz(self, tg_name: str) -> Optional[timezone]: ...
    async def set_tz(self, tg_name: str, offset: int) -> None: ...
    async def get_reminders_tab(self, tg_name: str, task_id: int) -> Optional[dict[str, datetime]]: ...
    async def get_reminder(self, tg_name: str, id_: str, task_id: int) -> Optional[datetime]: ...
    async def delete_reminders(self, tg_name: str, reminders_ids: list[str], task_id: int) -> None: ...
    async def delete_all_reminders(self, tg_name: str, task_id: int) -> list[str]: ...
    async def set_reminder(self, tg_name: str, eta: datetime, id_: str, task_id: int) -> None: ...


class SyncStorageInterface(Protocol):
    def get_reminder(self, tg_name: str, id_: str, task_id: int) -> Optional[datetime]: ...
    def delete_reminders(self, tg_name: str, reminders_ids: list[str], task_id: int) -> None: ...
