from typing import Protocol, Optional
from datetime import timezone, datetime


class StorageInterface(Protocol):
    async def get_tz(self, tg_name: str) -> Optional[timezone]: ...
    async def set_tz(self, tg_name: str, offset: int) -> None: ...
    async def get_remid_eta(self, tg_name: str) -> Optional[datetime]: ...
    async def set_remind_eta(self, tg_name: str, eta: datetime) -> None: ...
