from typing import Protocol
from src.domain.entities import Task


class TaskRepositoryInterface(Protocol):
    async def get_active_tasks(self, tg_name: str) -> list[Task]: ...
    async def get_finished_tasks(self, tg_name: str) -> list[Task]: ...
    async def save(task: Task) -> None: ...
