"""cascade deleting subtasks and user tasks when deleted user

Revision ID: 67380eca4ed1
Revises: 1c35861fdf62
Create Date: 2025-06-22 09:27:12.604263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67380eca4ed1'
down_revision: Union[str, None] = '1c35861fdf62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_groups_id'), 'groups', ['id'])
    op.create_unique_constraint(op.f('uq_tasks_id'), 'tasks', ['id'])
    op.drop_constraint(op.f('fk_tasks_user_id_users'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('fk_tasks_task_id_tasks'), 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tasks_user_id_users'), 'tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_tasks_task_id_tasks'), 'tasks', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_users_id'), 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_id'), 'users', type_='unique')
    op.drop_constraint(op.f('fk_tasks_task_id_tasks'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('fk_tasks_user_id_users'), 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tasks_task_id_tasks'), 'tasks', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(op.f('fk_tasks_user_id_users'), 'tasks', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('uq_tasks_id'), 'tasks', type_='unique')
    op.drop_constraint(op.f('uq_groups_id'), 'groups', type_='unique')
    # ### end Alembic commands ###
