"""added relation between users and tasks

Revision ID: c5bc886d7874
Revises: d79896ecec05
Create Date: 2025-06-12 06:13:06.063568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5bc886d7874'
down_revision: Union[str, None] = 'd79896ecec05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_groups_id'), 'groups', ['id'])
    op.create_unique_constraint(op.f('uq_subtasks_id'), 'subtasks', ['id'])
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('uq_tasks_id'), 'tasks', ['id'])
    op.create_foreign_key(op.f('fk_tasks_user_id_users'), 'tasks', 'users', ['user_id'], ['id'])
    op.drop_column('tasks', 'user')
    op.create_unique_constraint(op.f('uq_users_id'), 'users', ['id'])
    op.drop_column('users', 'tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tasks', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('uq_users_id'), 'users', type_='unique')
    op.add_column('tasks', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_tasks_user_id_users'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('uq_tasks_id'), 'tasks', type_='unique')
    op.drop_column('tasks', 'user_id')
    op.drop_constraint(op.f('uq_subtasks_id'), 'subtasks', type_='unique')
    op.drop_constraint(op.f('uq_groups_id'), 'groups', type_='unique')
    # ### end Alembic commands ###
